// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFIkjZKaOdtNg_tbX8PifB9JA2TyShfZ8',
    appId: '1:306846047939:web:1ca09140dd95e962eccc76',
    messagingSenderId: '306846047939',
    projectId: 'gofood-10655',
    authDomain: 'gofood-10655.firebaseapp.com',
    storageBucket: 'gofood-10655.firebasestorage.app',
    measurementId: 'G-TQRRK80F4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6aWPBHdtX1yuzo0aMrSGFJsX9Fs7pfPg',
    appId: '1:306846047939:android:f58036a0296b06edeccc76',
    messagingSenderId: '306846047939',
    projectId: 'gofood-10655',
    storageBucket: 'gofood-10655.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpYPzt0YloGhzwEcenuLwjRRAGqq5LVoE',
    appId: '1:306846047939:ios:cebdbbf44c8edf20eccc76',
    messagingSenderId: '306846047939',
    projectId: 'gofood-10655',
    storageBucket: 'gofood-10655.firebasestorage.app',
    iosBundleId: 'com.example.gofood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpYPzt0YloGhzwEcenuLwjRRAGqq5LVoE',
    appId: '1:306846047939:ios:cebdbbf44c8edf20eccc76',
    messagingSenderId: '306846047939',
    projectId: 'gofood-10655',
    storageBucket: 'gofood-10655.firebasestorage.app',
    iosBundleId: 'com.example.gofood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFIkjZKaOdtNg_tbX8PifB9JA2TyShfZ8',
    appId: '1:306846047939:web:ae0a5b7e3ac271b5eccc76',
    messagingSenderId: '306846047939',
    projectId: 'gofood-10655',
    authDomain: 'gofood-10655.firebaseapp.com',
    storageBucket: 'gofood-10655.firebasestorage.app',
    measurementId: 'G-5XGJQ55LG7',
  );
}
